[build.environment]
  NPM_FLAGS = "--prefix=/dev/null"
  NODE_VERSION = "14"

[build]
  publish = "dist"
  command = ""

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = '/*'
  [headers.values]
    Content-Security-Policy = "default-src 'self' gstc.neuronet.io *.neuronet.io;"