// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CarbonCampsite: typeof import('~icons/carbon/campsite')['default']
    CarbonWarning: typeof import('~icons/carbon/warning')['default']
    EquipmentDetails: typeof import('./components/EquipmentDetails.vue')['default']
    EquipmentList: typeof import('./components/EquipmentList.vue')['default']
    FooterOriginal: typeof import('./components/FooterOriginal.vue')['default']
    Modal: typeof import('./components/Modal.vue')['default']
    README: typeof import('./components/README.md')['default']
    RentDetails: typeof import('./components/RentDetails.vue')['default']
    RentScheduler: typeof import('./components/RentScheduler.vue')['default']
    Scheduler: typeof import('./components/Scheduler.vue')['default']
    SeatDetails: typeof import('./components/SeatDetails.vue')['default']
    SeatList: typeof import('./components/SeatList.vue')['default']
  }
}

export { }
