// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Calendar: typeof import('./components/Calendar.vue')['default']
    'Calendar copy': typeof import('./components/Calendar copy.vue')['default']
    CarbonCampsite: typeof import('~icons/carbon/campsite')['default']
    CarbonDicomOverlay: typeof import('~icons/carbon/dicom-overlay')['default']
    CarbonLanguage: typeof import('~icons/carbon/language')['default']
    CarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonPedestrian: typeof import('~icons/carbon/pedestrian')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    CarbonWarning: typeof import('~icons/carbon/warning')['default']
    EquipmentDetails: typeof import('./components/EquipmentDetails.vue')['default']
    EquipmentList: typeof import('./components/EquipmentList.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    'Footer copy': typeof import('./components/FooterOriginal.vue')['default']
    FooterOriginal: typeof import('./components/FooterOriginal.vue')['default']
    'FooterOriginal copy': typeof import('./components/FooterOriginal copy.vue')['default']
    Modal: typeof import('./components/Modal.vue')['default']
    NavBar: typeof import('./components/NavBar.vue')['default']
    README: typeof import('./components/README.md')['default']
    RentDetails: typeof import('./components/RentDetails.vue')['default']
    RentList: typeof import('./components/RentScheduler.vue')['default']
    RentScheduler: typeof import('./components/RentScheduler.vue')['default']
    Scheduler: typeof import('./components/Scheduler.vue')['default']
    SeatDetails: typeof import('./components/SeatDetails.vue')['default']
    'SeatDetails copy': typeof import('./components/RentDetails.vue')['default']
    SeatList: typeof import('./components/SeatList.vue')['default']
    'SeatList copy': typeof import('./components/RentScheduler.vue')['default']
  }
}

export { }
